{% set name = "mamba" %}
{% set version = "0.0.2" %}
{% set sha256 = "a68ff92ba96cf2c1663e685dcf15dfe81bc8a8ef7e041ec78c17119431b3e410" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11 2.2.*
    - conda
    - libsolv
  run:
    - python
    - conda

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help

about:
  home: https://github.com/QuantStack/mamba
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A faster conda?!'
  description: 'mamba, a (hopefully faster) reimplementation of parts of conda.'
  dev_url: https://github.com/QuantStack/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
