{% set name = "mamba" %}
{% set version = "0.4.1" %}
{% set sha256 = "985e8de16d64ec1bc90104f0c701500fa70f7f2eb1c7b79c7aea9a6876248e8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - placeholder.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11
    - conda >=4.8
    - libsolv >=0.7.14
    - libcurl
    - openssl
    - libarchive
    - nlohmann_json
  run:
    - python
    - conda >=4.8

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help
    # these tests work when run on win, but for some reason not during conda build
    - mamba create -n test_py2 python=2.7 --dry-run  # [linux]
    - mamba install xtensor xsimd -c conda-forge --dry-run  # [linux and x86_64]

about:
  home: https://github.com/QuantStack/mamba
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
  description: A fast drop-in alternative to conda, using libsolv for dependency resolution
  dev_url: https://github.com/QuantStack/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
